version: "3"
services:
  database:
    image: postgres
    container_name: database
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - volume_database:/var/lib/postgresql/data

  app_node:
    build: .
    container_name: app_node
    ports:
      - 80:4000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - database

volumes:
  volume_database:
